# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!

{ fetchNuGet }: [
  (fetchNuGet { pname = "Google.Protobuf"; version = "3.21.5"; sha256 = "0vziz26dvwjl7hs4xvbbinfn87q4dfdksnr55w2d36mac3cgak7r"; })
  (fetchNuGet { pname = "Grpc.Tools"; version = "2.47.0"; sha256 = "0ibi57cnkxxxzyyjzmv6dgpz365mafbp4h8ghg3417z095kcd78c"; })
  (fetchNuGet { pname = "Microsoft.AspNetCore.App.Ref"; version = "7.0.12"; sha256 = "0g27vqma0bfnhf4in633dyh47zv8hdnwlahv7kkbs6fnrl41nckb"; })
  (fetchNuGet { pname = "Microsoft.AspNetCore.App.Runtime.linux-arm64"; version = "7.0.12"; sha256 = "0bjsqp0akvg879awrw8pv9prjw0bmj59l196r5dxgz5d8c48v5c1"; })
  (fetchNuGet { pname = "Microsoft.AspNetCore.App.Runtime.linux-x64"; version = "7.0.12"; sha256 = "1n5g9iwk7z3ms5anad35jgqvdk5bl7kxcy8659ivlq56pii7lv37"; })
  (fetchNuGet { pname = "Microsoft.AspNetCore.App.Runtime.osx-arm64"; version = "7.0.12"; sha256 = "1q4yj4qmk4ys2lr9qd8dvvfrjascqdva09k8azxirkshmsgkx0rm"; })
  (fetchNuGet { pname = "Microsoft.AspNetCore.App.Runtime.osx-x64"; version = "7.0.12"; sha256 = "073ipw7m1cxyzywbcc2l4q9dnf9x63japazhhxf3fdhbkppvhmk5"; })
  (fetchNuGet { pname = "Microsoft.DotNet.ILCompiler"; version = "8.0.0-rc.2.23479.6"; sha256 = "0icj0ca8mjc5di7w0nr7v20zqss2dvp6hrkwfd8gbw518wffyhd8"; })
  (fetchNuGet { pname = "Microsoft.NET.ILLink.Tasks"; version = "8.0.0-rc.2.23479.6"; sha256 = "17vix7p2did14s8jqb57cai5nfcdxr3n79wsl07ddy919fmvhff0"; })
  (fetchNuGet { pname = "Microsoft.NETCore.App.Host.linux-arm64"; version = "7.0.12"; sha256 = "1sr1dxfadx5zc7w2iq75jksms3bf4f818hrpcgr8kr0n2vdmwb3h"; })
  (fetchNuGet { pname = "Microsoft.NETCore.App.Host.linux-x64"; version = "7.0.12"; sha256 = "0snp0pzb4amhrxys1g4591llsmlzg8lj3g8q2v31rh5jlvyxy705"; })
  (fetchNuGet { pname = "Microsoft.NETCore.App.Host.osx-arm64"; version = "7.0.12"; sha256 = "14h8kg91bzc1zifigyllb8q788c41h8ixlb58ikyhbhm803l7m4s"; })
  (fetchNuGet { pname = "Microsoft.NETCore.App.Host.osx-x64"; version = "7.0.12"; sha256 = "1jqvpl930pxjzzy3m3339025yrbg3a3j5l6cvyrqkdad34kzvn6y"; })
  (fetchNuGet { pname = "Microsoft.NETCore.App.Ref"; version = "7.0.12"; sha256 = "0vl46nd5bm563v3shkwksss3zs0b57vzbrgyk0whj71iqfq2kdir"; })
  (fetchNuGet { pname = "Microsoft.NETCore.App.Runtime.linux-arm64"; version = "7.0.12"; sha256 = "13bkbjkmp0ij9mjp3xnfmlf9vlkidl5d1650fbl7mxbf9krz92mv"; })
  (fetchNuGet { pname = "Microsoft.NETCore.App.Runtime.linux-x64"; version = "7.0.12"; sha256 = "1dg4f3iid6f5q66v4dpynarmxqnngrwqj3x8i4vsqawpqy2z1p5y"; })
  (fetchNuGet { pname = "Microsoft.NETCore.App.Runtime.osx-arm64"; version = "7.0.12"; sha256 = "1sfvmhn2597526llq33cvjhhg4h7frwvl5yrbgql3qwyk5b5h25p"; })
  (fetchNuGet { pname = "Microsoft.NETCore.App.Runtime.osx-x64"; version = "7.0.12"; sha256 = "191py5cjyd44rvnz915svhxc1190682bqz6rc3yyv2q2w8kc0apy"; })
  (fetchNuGet { pname = "QRCoder"; version = "1.4.3"; sha256 = "1hmlqbdyq5n9bsmns5h0dwcxpd2jvqr9a2y6dyc9kbjmc8j1dpla"; })
  (fetchNuGet { pname = "runtime.osx-arm64.Microsoft.DotNet.ILCompiler"; version = "8.0.0-rc.2.23479.6"; sha256 = "0kxkmm9sfvd19mc6gswfsmmwdgqzl8fmdmfgv37ns9my2d6c3adx"; })
  (fetchNuGet { pname = "SharpZipLib"; version = "1.4.2"; sha256 = "0ijrzz2szxjmv2cipk7rpmg14dfaigdkg7xabjvb38ih56m9a27y"; })
  (fetchNuGet { pname = "System.CommandLine"; version = "2.0.0-beta4.22272.1"; sha256 = "1iy5hwwgvx911g3yq65p4zsgpy08w4qz9j3h0igcf7yci44vw8yd"; })
]
