# C
[candy]
src.git = "https://github.com/lanthora/candy"
fetch.github = "lanthora/candy"

[koboldcpp]
src.git = "https://github.com/LostRuins/koboldcpp"
fetch.github = "LostRuins/koboldcpp"
git.fetchSubmodules = true

[suyu]
src.git = "https://git.suyu.dev/suyu/suyu"
fetch.git = "https://git.suyu.dev/suyu/suyu"
git.fetchSubmodules = true

# Go
[open-snell]
src.git = "https://github.com/icpz/open-snell"
fetch.github = "icpz/open-snell"

[swgp-go]
src.git = "https://github.com/database64128/swgp-go"
src.branch = "main"
fetch.github = "database64128/swgp-go"

# Python
[idntag]
src.git = "https://github.com/d99kris/idntag"
fetch.github = "d99kris/idntag"

[pynat]
src.git = "https://github.com/aarant/pynat"
fetch.github = "aarant/pynat"

[pystun3]
src.git = "https://github.com/talkiq/pystun3"
fetch.github = "talkiq/pystun3"

# Rust
[ab-av1]
src.git = "https://github.com/alexheretic/ab-av1"
fetch.github = "alexheretic/ab-av1"

[Anime4K-rs]
src.git = "https://github.com/andraantariksa/Anime4K-rs"
fetch.github = "andraantariksa/Anime4K-rs"

[av1an]
src.git = "https://github.com/master-of-zen/av1an"
fetch.github = "master-of-zen/av1an"

[ncmdump_rs]
src.git = "https://github.com/iqiziqi/ncmdump.rs"
fetch.github = "iqiziqi/ncmdump.rs"

[onedrive-fuse]
src.git = "https://github.com/oxalica/onedrive-fuse"
fetch.github = "oxalica/onedrive-fuse"

[rescrobbled]
src.git = "https://github.com/InputUsername/rescrobbled"
fetch.github = "InputUsername/rescrobbled"

[sakaya]
src.git = "https://github.com/donovanglover/sakaya"
fetch.github = "donovanglover/sakaya"

[waylyrics]
src.git = "https://github.com/waylyrics/waylyrics"
fetch.github = "waylyrics/waylyrics"






[qcm]
src.git = "https://github.com/hypengw/Qcm"
fetch.github = "hypengw/Qcm"
git.fetchSubmodules = true





[forkgram]
src.git = "https://github.com/forkgram/tdesktop"
fetch.github = "forkgram/tdesktop"
git.fetchSubmodules = true

# Shell
[reflac]
src.git = "https://github.com/chungy/reflac"
fetch.github = "chungy/reflac"
