[swgp-go]
src.git = "https://github.com/database64128/swgp-go"
src.branch = "main"
fetch.github = "database64128/swgp-go"

[ab-av1]
src.git = "https://github.com/alexheretic/ab-av1"
fetch.github = "alexheretic/ab-av1"

[qcm]
src.git = "https://github.com/hypengw/Qcm"
fetch.github = "hypengw/Qcm"
git.fetchSubmodules = true

[candy]
src.git = "https://github.com/lanthora/candy"
fetch.github = "lanthora/candy"

[suyu]
src.git = "https://git.suyu.dev/suyu/suyu"
fetch.git = "https://git.suyu.dev/suyu/suyu"
git.fetchSubmodules = true

[forkgram]
src.git = "https://github.com/forkgram/tdesktop"
fetch.github = "forkgram/tdesktop"
git.fetchSubmodules = true

[koboldcpp]
src.git = "https://github.com/LostRuins/koboldcpp"
fetch.github = "LostRuins/koboldcpp"
git.fetchSubmodules = true

[av1an]
src.git = "https://github.com/master-of-zen/av1an"
fetch.github = "master-of-zen/av1an"

[waylyrics]
src.git = "https://github.com/waylyrics/waylyrics"
fetch.github = "waylyrics/waylyrics"

[rescrobbled]
src.git = "https://github.com/InputUsername/rescrobbled"
fetch.github = "InputUsername/rescrobbled"

[onedrive-fuse]
src.git = "https://github.com/oxalica/onedrive-fuse"
fetch.github = "oxalica/onedrive-fuse"

[sakaya]
src.git = "https://github.com/donovanglover/sakaya"
fetch.github = "donovanglover/sakaya"

[Anime4K-rs]
src.git = "https://github.com/andraantariksa/Anime4K-rs"
fetch.github = "andraantariksa/Anime4K-rs"

[ncmdump_rs]
src.git = "https://github.com/iqiziqi/ncmdump.rs"
fetch.github = "iqiziqi/ncmdump.rs"
