# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  ab-av1 = {
    pname = "ab-av1";
    version = "e65965f74725a1f6d081c583af91af81f68a2268";
    src = fetchFromGitHub {
      owner = "alexheretic";
      repo = "ab-av1";
      rev = "e65965f74725a1f6d081c583af91af81f68a2268";
      fetchSubmodules = false;
      sha256 = "sha256-fUVeeRgfDEggSx1Zpqlneu3W+afR8+6fAnD0F2QQ5uI=";
    };
    date = "2024-03-09";
  };
  candy = {
    pname = "candy";
    version = "4b9e79aaceb53868ea09988d756a1bd82a652612";
    src = fetchFromGitHub {
      owner = "lanthora";
      repo = "candy";
      rev = "4b9e79aaceb53868ea09988d756a1bd82a652612";
      fetchSubmodules = false;
      sha256 = "sha256-4X/X2VmjH8OIMt82uW7TcW8Ojta9C57By1pkeF9ysIY=";
    };
    date = "2024-04-01";
  };
  qcm = {
    pname = "qcm";
    version = "ab29b2cd7a4bc554be2d8dc8401e5dfd7df2c6c6";
    src = fetchFromGitHub {
      owner = "hypengw";
      repo = "Qcm";
      rev = "ab29b2cd7a4bc554be2d8dc8401e5dfd7df2c6c6";
      fetchSubmodules = true;
      sha256 = "sha256-uJwreBXSSH6uXd14e3Ln2rHvk+rrOvmUtkeRIU3sOSw=";
    };
    date = "2024-02-25";
  };
  swgp-go = {
    pname = "swgp-go";
    version = "ff0d7b3552d6b6c1651791f5fab2de5075746e36";
    src = fetchFromGitHub {
      owner = "database64128";
      repo = "swgp-go";
      rev = "ff0d7b3552d6b6c1651791f5fab2de5075746e36";
      fetchSubmodules = false;
      sha256 = "sha256-oSkIBOC71jgWJEMpv7q0Rd11KRIGxbpYOG2gK8OMLRk=";
    };
    date = "2024-03-12";
  };
}
