# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  Anime4K-rs = {
    pname = "Anime4K-rs";
    version = "a47a8ac21f81d6a3bcbdf6fc338b6546f1a51d29";
    src = fetchFromGitHub {
      owner = "andraantariksa";
      repo = "Anime4K-rs";
      rev = "a47a8ac21f81d6a3bcbdf6fc338b6546f1a51d29";
      fetchSubmodules = false;
      sha256 = "sha256-7CvYbc4U9kIwV2ELkd4lqKC1ynCwqizpXBXJamSGDig=";
    };
    date = "2020-08-09";
  };
  aichat = {
    pname = "aichat";
    version = "4ddc28d40c238bb67d750d022bd3ca8a1a31cd0c";
    src = fetchFromGitHub {
      owner = "sigoden";
      repo = "aichat";
      rev = "4ddc28d40c238bb67d750d022bd3ca8a1a31cd0c";
      fetchSubmodules = false;
      sha256 = "sha256-M79OlEcj4g0PIWDRcBvEjPbkjoeHz1drq6oEFSnz8Do=";
    };
    date = "2025-12-01";
  };
  av1an = {
    pname = "av1an";
    version = "93b4948d0c3fb705decc8b06b240db11019a8808";
    src = fetchFromGitHub {
      owner = "master-of-zen";
      repo = "av1an";
      rev = "93b4948d0c3fb705decc8b06b240db11019a8808";
      fetchSubmodules = false;
      sha256 = "sha256-P2m8xD3w0D8pz1bUzw3HXK689v4tkLzR5Ej3PWWI5AA=";
    };
    date = "2025-12-08";
  };
  bypy = {
    pname = "bypy";
    version = "d5a0a75d9d2a7df0041e4bf5ce5035e54f6ea6c3";
    src = fetchFromGitHub {
      owner = "houtianze";
      repo = "bypy";
      rev = "d5a0a75d9d2a7df0041e4bf5ce5035e54f6ea6c3";
      fetchSubmodules = false;
      sha256 = "sha256-FO9v24J+N5Y4zGb+U9jqSLZ+++d6uUsJuT5p7pSrdX0=";
    };
    date = "2025-04-02";
  };
  candy = {
    pname = "candy";
    version = "f5e40a02b9e7dd2692cd92efcca68b1168a9426e";
    src = fetchFromGitHub {
      owner = "lanthora";
      repo = "candy";
      rev = "f5e40a02b9e7dd2692cd92efcca68b1168a9426e";
      fetchSubmodules = false;
      sha256 = "sha256-NjW2zK0eC2iPFMkspc7izn0XTSPW0+GNJ8pyVpwQRZM=";
    };
    date = "2025-11-30";
  };
  fww-checkin-rs = {
    pname = "fww-checkin-rs";
    version = "92ce21ff1556e709384c6e817157488db2a9eb7d";
    src = fetchFromGitHub {
      owner = "1235467";
      repo = "fww-checkin-rs";
      rev = "92ce21ff1556e709384c6e817157488db2a9eb7d";
      fetchSubmodules = false;
      sha256 = "sha256-aGYHwuMhot9RQ2PXJhQBzHljXBVcbuaO3r6/gWK/jIU=";
    };
    date = "2024-11-16";
  };
  hyprland = {
    pname = "hyprland";
    version = "abffe75088e2d776e14e5dbd726a835fa157df9a";
    src = fetchFromGitHub {
      owner = "hyprwm";
      repo = "Hyprland";
      rev = "abffe75088e2d776e14e5dbd726a835fa157df9a";
      fetchSubmodules = true;
      sha256 = "sha256-Vbfk4XxTP9pBtyUUXLCFCzK+/a3XlYkpS0QvePnlTFk=";
    };
    date = "2025-12-22";
  };
  hyprwayland-scanner = {
    pname = "hyprwayland-scanner";
    version = "f6cf414ca0e16a4d30198fd670ec86df3c89f671";
    src = fetchFromGitHub {
      owner = "hyprwm";
      repo = "hyprwayland-scanner";
      rev = "f6cf414ca0e16a4d30198fd670ec86df3c89f671";
      fetchSubmodules = true;
      sha256 = "sha256-Uan1Nl9i4TF/kyFoHnTq1bd/rsWh4GAK/9/jDqLbY5A=";
    };
    date = "2025-11-20";
  };
  idntag = {
    pname = "idntag";
    version = "62ddd08b6597fdfa8f2cb60ef6b1ce13cbe64c4d";
    src = fetchFromGitHub {
      owner = "d99kris";
      repo = "idntag";
      rev = "62ddd08b6597fdfa8f2cb60ef6b1ce13cbe64c4d";
      fetchSubmodules = false;
      sha256 = "sha256-71Fhl7ZKSSpwhaT3hAILZ44BdglfhJNFMLBjHSEKA7s=";
    };
    date = "2025-11-29";
  };
  libdrm = {
    pname = "libdrm";
    version = "369990d9660a387f618d0eedc341eb285016243b";
    src = fetchgit {
      url = "https://gitlab.freedesktop.org/mesa/drm";
      rev = "369990d9660a387f618d0eedc341eb285016243b";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-kOaTjBeo4IsfWEk/JBTNId5ikrnpoc9DEjIl7DUd2yE=";
    };
    date = "2025-12-19";
  };
  llamafile = {
    pname = "llamafile";
    version = "9509d911179dcb18ca61ee9e45de26d29c4f9bd5";
    src = fetchFromGitHub {
      owner = "Mozilla-Ocho";
      repo = "llamafile";
      rev = "9509d911179dcb18ca61ee9e45de26d29c4f9bd5";
      fetchSubmodules = false;
      sha256 = "sha256-+Blmg0hBXSBxQWvdKm6LL5bdHSVHLVrYdkvBR6ZbQoY=";
    };
    date = "2025-11-05";
  };
  mieru = {
    pname = "mieru";
    version = "26af2fc41989aefe3fda5ea507b52f4b7eb88695";
    src = fetchFromGitHub {
      owner = "enfein";
      repo = "mieru";
      rev = "26af2fc41989aefe3fda5ea507b52f4b7eb88695";
      fetchSubmodules = false;
      sha256 = "sha256-YfvPzp2E3yGZT+yRkvHDSovwFJ2+CKCvStjIXXoIEKA=";
    };
    date = "2025-12-18";
  };
  nbfc-linux = {
    pname = "nbfc-linux";
    version = "4b24c0a7c0f274ec948b5edcd3e12d639177ddf3";
    src = fetchFromGitHub {
      owner = "nbfc-linux";
      repo = "nbfc-linux";
      rev = "4b24c0a7c0f274ec948b5edcd3e12d639177ddf3";
      fetchSubmodules = false;
      sha256 = "sha256-GpCDz4ZJGjV36cgyfbkNy2HSvXg8BtOpQzTOUg2T/Lo=";
    };
    date = "2025-12-22";
  };
  ncmdump_rs = {
    pname = "ncmdump_rs";
    version = "2e7f77779f55f914fb505d996b16e829028240e3";
    src = fetchFromGitHub {
      owner = "iqiziqi";
      repo = "ncmdump.rs";
      rev = "2e7f77779f55f914fb505d996b16e829028240e3";
      fetchSubmodules = false;
      sha256 = "sha256-ryxjZFTknWEGHESo0OcoBv/+rCx+rCifoSsqNUaF+FM=";
    };
    date = "2024-09-23";
  };
  onedrive-fuse = {
    pname = "onedrive-fuse";
    version = "15f8e5ee98b20d18ea40cdbbb63d1ae1a30d285f";
    src = fetchFromGitHub {
      owner = "oxalica";
      repo = "onedrive-fuse";
      rev = "15f8e5ee98b20d18ea40cdbbb63d1ae1a30d285f";
      fetchSubmodules = false;
      sha256 = "sha256-1O2DfG+cRK8EOTQiStH37erD4nvfz7YnxPITe4TB5hQ=";
    };
    date = "2024-12-26";
  };
  open-snell = {
    pname = "open-snell";
    version = "8d2645b8394b20dba744a860655e3092fc8ae052";
    src = fetchFromGitHub {
      owner = "icpz";
      repo = "open-snell";
      rev = "8d2645b8394b20dba744a860655e3092fc8ae052";
      fetchSubmodules = false;
      sha256 = "sha256-/gILrDXOXDYQ3cTUMbjHAzITdtC2O+4XO0pp1ulRAM4=";
    };
    date = "2022-04-19";
  };
  pynat = {
    pname = "pynat";
    version = "22a8f2a467bfb95003d35b139dad9fd5a1ca4e9d";
    src = fetchFromGitHub {
      owner = "aarant";
      repo = "pynat";
      rev = "22a8f2a467bfb95003d35b139dad9fd5a1ca4e9d";
      fetchSubmodules = false;
      sha256 = "sha256-2ig0mvePKglxz3IpBdiWsTfNJ9koODn34gHVRqbdwPk=";
    };
    date = "2022-08-20";
  };
  pystun3 = {
    pname = "pystun3";
    version = "5fdc6fa446924b575250acf853a8f7eea0c8b8c9";
    src = fetchFromGitHub {
      owner = "talkiq";
      repo = "pystun3";
      rev = "5fdc6fa446924b575250acf853a8f7eea0c8b8c9";
      fetchSubmodules = false;
      sha256 = "sha256-1QnfEHzkvjWURsApvTi4aVVz3MBNieQmVofmqUmgb4k=";
    };
    date = "2024-06-28";
  };
  qcm = {
    pname = "qcm";
    version = "9760efd2f2e58d51cd5932a49b1657450aa2baaf";
    src = fetchFromGitHub {
      owner = "hypengw";
      repo = "Qcm";
      rev = "9760efd2f2e58d51cd5932a49b1657450aa2baaf";
      fetchSubmodules = true;
      sha256 = "sha256-b9LKiRgD0V4zo639Rs15RmhHvqc7iYNo4/2sm1H+UhA=";
    };
    date = "2025-12-23";
  };
  reflac = {
    pname = "reflac";
    version = "a2dcaa2f5d3d23cf121934d5ff0e4d169a8f7a64";
    src = fetchFromGitHub {
      owner = "chungy";
      repo = "reflac";
      rev = "a2dcaa2f5d3d23cf121934d5ff0e4d169a8f7a64";
      fetchSubmodules = false;
      sha256 = "sha256-vrHDzDTrLPaDHXwgWJplCOQT6YdcWaEu28Rx1yXlgNk=";
    };
    date = "2021-08-16";
  };
  rescrobbled = {
    pname = "rescrobbled";
    version = "ad1ff09c98a6478a641b9a61acaf1ad13c1d9bfe";
    src = fetchFromGitHub {
      owner = "InputUsername";
      repo = "rescrobbled";
      rev = "ad1ff09c98a6478a641b9a61acaf1ad13c1d9bfe";
      fetchSubmodules = false;
      sha256 = "sha256-+5BkM4L2eB54idZ6X2ESw6ERMhG5CM4AF4BMEJm3xLU=";
    };
    date = "2025-06-12";
  };
  sakaya = {
    pname = "sakaya";
    version = "449d31702e9d91219eb3f005087308972fb6d7f2";
    src = fetchFromGitHub {
      owner = "donovanglover";
      repo = "sakaya";
      rev = "449d31702e9d91219eb3f005087308972fb6d7f2";
      fetchSubmodules = false;
      sha256 = "sha256-joPvzJwuCE0thZzKPSsK5k37EIIYHomx+Y8t+gZunLk=";
    };
    date = "2025-05-01";
  };
  suyu = {
    pname = "suyu";
    version = "ee365bad9501c73ff49936e72ec91cd9c3ce5c24";
    src = fetchgit {
      url = "https://git.suyu.dev/suyu/suyu";
      rev = "ee365bad9501c73ff49936e72ec91cd9c3ce5c24";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-vw9VcSbCaG4MS0PL/fJ73CDALLbd3n0CBT7gkyp5hRc=";
    };
    date = "2024-10-06";
  };
  sway = {
    pname = "sway";
    version = "dbe86400357fb1d41693874f7d9f70f285fd1737";
    src = fetchFromGitHub {
      owner = "swaywm";
      repo = "sway";
      rev = "dbe86400357fb1d41693874f7d9f70f285fd1737";
      fetchSubmodules = true;
      sha256 = "sha256-/X+pBt45Zqq6G7z/9phbfolCvR97/fyKDpSju6T1YhU=";
    };
    date = "2025-12-21";
  };
  swgp-go = {
    pname = "swgp-go";
    version = "67acf1cbcbfebca93ac1d8d09b775e6cf161ab27";
    src = fetchFromGitHub {
      owner = "database64128";
      repo = "swgp-go";
      rev = "67acf1cbcbfebca93ac1d8d09b775e6cf161ab27";
      fetchSubmodules = false;
      sha256 = "sha256-YadrpGy2swD3DUv+vrUhW05WijV5yQfEI1DqCAIcSVI=";
    };
    date = "2025-12-12";
  };
  wayland = {
    pname = "wayland";
    version = "99638501a1314e68c79176fa2cafa3bbe6cf55ea";
    src = fetchgit {
      url = "https://gitlab.freedesktop.org/wayland/wayland";
      rev = "99638501a1314e68c79176fa2cafa3bbe6cf55ea";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-2Tz/Owuc8gBHg7CSd4wq+mvowsjm0nbLnasyabVslGg=";
    };
    date = "2025-12-12";
  };
  wayland-protocols = {
    pname = "wayland-protocols";
    version = "a6ac326be335c8914ac8ed8114429f13a0e30f1b";
    src = fetchgit {
      url = "https://gitlab.freedesktop.org/wayland/wayland-protocols";
      rev = "a6ac326be335c8914ac8ed8114429f13a0e30f1b";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-FMen+2uY1JarJgITHhFO921WDJamGZ3AniNrg7RfQ+8=";
    };
    date = "2025-12-16";
  };
  waylyrics = {
    pname = "waylyrics";
    version = "1a5f411af9c58fe5ac3c2f29f066d97995597bb9";
    src = fetchFromGitHub {
      owner = "waylyrics";
      repo = "waylyrics";
      rev = "1a5f411af9c58fe5ac3c2f29f066d97995597bb9";
      fetchSubmodules = false;
      sha256 = "sha256-IG1fDNukL+ccsZwkk7a/9fIcvSJa2CbXs2C55k8t+Ac=";
    };
    date = "2025-12-14";
  };
  wlroots = {
    pname = "wlroots";
    version = "9119b8aa851c413b79295f2a913124f0eed536d4";
    src = fetchgit {
      url = "https://gitlab.freedesktop.org/wlroots/wlroots";
      rev = "9119b8aa851c413b79295f2a913124f0eed536d4";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-oCaK4XDz1yNnrW6a2036KffapJ0u2/fLNH0XWOJdw+c=";
    };
    date = "2025-12-22";
  };
}
